# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VEKXPSr1gkYmWZlRe2LhK6qNqlQyvLv
"""

print("Hello World")

input("Test input")

#it is an interpreted language not a compiled language
metres = 100
feet = 3.2008*metres
metres = 200
print(feet)
print(metres)

# indentation matters in python also to check if two values are equal put == not =
x = float(input("any number"))
y = float(input("any number part 2"))
if x == y:
  print("they are equal")
else:
  print("they are not equal")

x= 2
while x==2:
  x=x+1
  print("lol")
  print(x)

# calculating factorial(using while loop)
n = float(input(""))
if n >0:
  y=n
  z=n
  while y>1:
    y= y-1
    z = z*y
print(z)

# Assignment0 (raised to the power of can be written as **)
import numpy as np
x = float(input(""))
print(x**2)
k = np.log2(x)
print(k)

# assignment 1
total_cost = float(input("cost of the home: "))
portion_down_payment = 0.25
current_savings = 0
r = 0.04
monthly_return_savings = current_savings*r/12
annual_salary = float(input("annual salary: "))
monthly_salary = annual_salary/12
portion_saved = float(input("portion of salary saved(in decimal form): "))

current_savings = portion_saved*monthly_salary

# range(start, stop, step) , start: first int, stop: last int, step: used to generate next int in seq, start deafults to 0, step defaults to 1
n = int(input("any int: "))
for i in range(0,4,2):
  print(i)
for i in range(n):
  print(i)

mysum  = 0
for i in range(10):
  mysum += i
print(mysum)
#Note: for loop does not do the operation when it reaches last case

#better factorial calculator:
n = int(input("enter any number: "))
m = 1
for i in range(1,n+1,1):
  m = m*i
print(m)

# code that loops a for loop over some range and prints how many even numbers are in that range:
# thoughts: gif ,
n = int(input("any int: "))
print(int(n/2 + 1))

# i%2 means remainder when i is divided by 2
# now using a for loop
even_numbers = 0
for i in range(n):
   if i%2== 0:
    even_numbers = even_numbers+1
print(even_numbers)
# Note :the for loop one is better because it can be done for any range whereas the other one can only be done one type of range

#Assume you are given a string of lowercase letters in var s. Count how many uique letters there are in the string
n = str(input("the string of letters: "))
s = str("")
no_of_letters = 0
for i in n:
  if i in s:
    no_of_letters = no_of_letters
  else:
    s = s+i
    no_of_letters = no_of_letters+1
print(no_of_letters)

# guess and check alg of integer square root
num = int(input("give number whose integer square root is to be found: "))
guess = 0

while num>= 0:
  if guess**2 == num:
    print("there is an integer square root which is "+ str(guess))
    break
  else:
    guess += 1
  if guess > num:
    print("there is no integer square root")
    break

# converting integers to binary (more uses of guess and check alg)
n = float(input("enter in base 10: "))
a = abs(n)
s= ""
while a != 0:
  k = str(a%2)
  s = k + s
  a= int(a/2)
if n<0:
  s = "-"+s
print("number in base 2 is: " + s)

# Converting farction fractions to binary

n = float(input("enter in base 10: "))
a = n
p = 0

{"loop and if to get power power of 2 which when multiplied to n gives a whole number"}
while (a*(2**p))%2 != 0 :
  p +=1

if (a*(2**(p-1)))%2 == 1:
  p -= 1

new_a = abs(a*(2**(p)))

{"converting the whole number into binary and shifting decimal place"}
s = ""
while new_a > 0:
  s = str(new_a%2) + s
  new_a = int(new_a/2)

k = float(s)/10**p
k_str = str(k)
print("the fraction in binary is: " + k_str)

